#include "PCH.h"

#include "PreviewMenu.h"

#include "utils/Logger.h"

namespace preview
{
	namespace
	{
		bool g_registered = false;

		// UI3DSceneManager::Render, Address Library ID 51855 on Skyrim SE 1.5.97.
		//
		// Hand-bound because CommonLibSSE does not carry it. The ID is version-specific and only
		// the 1.5.97 one has been established, so this refuses to run on any other runtime rather
		// than calling whatever happens to live at that address - a wrong address here is a crash,
		// not a compile error (rule 44).
		void RenderUIScene()
		{
			static const bool supported = [] {
				const auto version = REL::Module::get().version();
				const bool ok = version.major() == 1 && version.minor() == 5 && version.patch() == 97;
				if (!ok)
				{
					logger::warn("preview menu: the UI 3D scene render is only mapped for Skyrim "
								 "1.5.97; this runtime is {}, so the preview will not draw",
								 version.string());
				}
				return ok;
			}();
			if (!supported) { return; }

			auto* scene = RE::UI3DSceneManager::GetSingleton();
			if (!scene) { return; }

			using func_t = void (*)(RE::UI3DSceneManager*, RE::INTERFACE_LIGHT_SCHEME, RE::NiCamera*, bool);
			static REL::Relocation<func_t> render{ REL::ID(51855) };

			// A null camera makes the function use the scene's own, which is the one our page has
			// been positioning all along.
			render(scene, RE::INTERFACE_LIGHT_SCHEME::kInventory, nullptr, false);
		}
	}

	PreviewMenu::PreviewMenu()
	{
		// The two flags the vanilla inventory has and the journal does not. kCustomRendering says
		// this menu is not drawn through a Scaleform movie, which is true - it draws nothing at
		// all - and kInventoryItemMenu is what marks it as one of the item-viewing family the UI
		// 3D scene is rendered for.
		menuFlags.set(RE::UI_MENU_FLAGS::kCustomRendering,
					  RE::UI_MENU_FLAGS::kInventoryItemMenu,
					  RE::UI_MENU_FLAGS::kRequiresUpdate,
					  // Not because the preview needs an offscreen target, but because PreDisplay
					  // is only called on menus that have this - and PreDisplay firing is the
					  // evidence that the game renders this menu at all.
					  RE::UI_MENU_FLAGS::kRendersOffscreenTargets);

		// Deliberately NOT kPausesGame and NOT kUsesCursor: this menu is invisible scaffolding, and
		// a settings page that silently paused the game or stole the cursor would be a bug the
		// player could see even though the menu itself is not.
		inputContext = Context::kNone;

		// The value IMenu itself defaults to, and what the inventory carries. It was 0 on the
		// first attempt, which put this menu below everything - and "rendered last" and "not
		// rendered" are indistinguishable from the outside.
		depthPriority = 3;

		// A REAL MOVIE. Some of what the game does for a menu is gated on it having a
		// GFxMovieView, and the entire purpose of this menu is to be treated as a real item menu -
		// so a menu with no movie may simply never qualify, however its flags are set.
		//
		// The movie is OURS and deliberately EMPTY: one blank frame, 20 bytes, generated by
		// .MD/scripts/make-blank-swf.py. Loading a vanilla SWF by path would have inherited
		// whatever that one draws (the fader paints the screen black), and another mod's file
		// would be someone else's asset.
		if (auto* scaleform = RE::BSScaleformManager::GetSingleton())
		{
			const bool loaded = scaleform->LoadMovieEx(
				this, "ApocryphaItemExplorer/preview",
				RE::BSScaleformManager::ScaleModeType::kShowAll, 0.0F,
				[](RE::GFxMovieDef*) {});
			logger::info("preview menu: blank movie {}", loaded ? "loaded" : "FAILED to load");
		}
	}

	RE::IMenu* PreviewMenu::Create()
	{
		return new PreviewMenu();
	}

	RE::UI_MESSAGE_RESULTS PreviewMenu::ProcessMessage(RE::UIMessage&)
	{
		// Every message is accepted and ignored. There is no movie to advance and no input to take.
		return RE::UI_MESSAGE_RESULTS::kHandled;
	}

	void PreviewMenu::PreDisplay()
	{
		// Once only: this is per-frame code, and the standing rule is that nothing there logs
		// unconditionally (rule 14).
		static bool logged = false;
		if (!logged)
		{
			logged = true;
			logger::info("preview menu: PreDisplay fired - the game IS rendering this menu");
		}

		// THE DRAW, in the one place it belongs: inside the game's own render pass, on a menu the
		// game is rendering. Every earlier attempt lacked that - the same idea from the framework's
		// Present hook drew nothing, and from a main-thread task drew nothing, because neither is
		// a render pass.
		//
		// UI3DSceneManager's RENDER is the call, and CommonLibSSE does not bind it - it binds six
		// methods of that class and this is not one of them. It was identified by dumping the
		// class's code block out of the running game (the on-disk exe is Steam-packed) and reading
		// it: of the fifteen functions in the block, exactly one touches both shader accumulators,
		// the camera, the lights, the shadow scene node and the lock, across 366 instructions and
		// 40 calls. Its prologue gives the signature - rcx this, edx compared against
		// currentlightScheme at +0x90, r8 a camera pointer that falls back to this->camera when
		// null, r9b a flag - so it is called here with the scene's own camera.
		RenderUIScene();
	}

	void RegisterPreviewMenu()
	{
		if (g_registered) { return; }

		auto* ui = RE::UI::GetSingleton();
		if (!ui)
		{
			// Rule 17: not ready is not never - this is called again at the next message.
			logger::debug("preview menu: the UI is not available yet; will register later");
			return;
		}

		ui->Register(PreviewMenu::MENU_NAME, PreviewMenu::Create);
		g_registered = true;
		logger::info("preview menu: registered \"{}\" (kCustomRendering | kInventoryItemMenu)",
					 std::string(PreviewMenu::MENU_NAME));
	}

	void SetPreviewMenuOpen(bool a_open)
	{
		if (!g_registered) { return; }
		if (PreviewMenuOpen() == a_open) { return; }

		auto* queue = RE::UIMessageQueue::GetSingleton();
		if (!queue) { return; }

		queue->AddMessage(RE::BSFixedString(std::string(PreviewMenu::MENU_NAME).c_str()),
						  a_open ? RE::UI_MESSAGE_TYPE::kShow : RE::UI_MESSAGE_TYPE::kHide,
						  nullptr);
		logger::info("preview menu: asked to {} it", a_open ? "open" : "close");
	}

	bool PreviewMenuOpen()
	{
		auto* ui = RE::UI::GetSingleton();
		return ui && ui->IsMenuOpen(PreviewMenu::MENU_NAME);
	}
}
