#include "PCH.h"

#include "PreviewMenu.h"

#include "Settings.h"

#include "utils/Logger.h"

namespace preview
{
	namespace
	{
		bool g_registered = false;

		// UI3DSceneManager::Render, Address Library ID 51855 on Skyrim SE 1.5.97.
		//
		// Hand-bound because CommonLibSSE does not carry it. The ID is version-specific and only
		// the 1.5.97 one has been established, so this refuses to run on any other runtime rather
		// than calling whatever happens to live at that address - a wrong address here is a crash,
		// not a compile error (rule 44).
		void RenderUIScene()
		{
			static const bool supported = [] {
				const auto version = REL::Module::get().version();
				const bool ok = version.major() == 1 && version.minor() == 5 && version.patch() == 97;
				if (!ok)
				{
					logger::warn("preview menu: the UI 3D scene render is only mapped for Skyrim "
								 "1.5.97; this runtime is {}, so the preview will not draw",
								 version.string());
				}
				return ok;
			}();
			if (!supported) { return; }

			auto* scene = RE::UI3DSceneManager::GetSingleton();
			if (!scene) { return; }

			using func_t = void (*)(RE::UI3DSceneManager*, RE::INTERFACE_LIGHT_SCHEME, RE::NiCamera*, bool);
			static REL::Relocation<func_t> render{ REL::ID(51855) };

			// A null camera makes the function use the scene's own, which is the one our page has
			// been positioning all along.
			render(scene, static_cast<RE::INTERFACE_LIGHT_SCHEME>(settings::preview::scheme),
				   nullptr, false);
		}
	}

	PreviewMenu::PreviewMenu()
	{
		// The two flags the vanilla inventory has and the journal does not. kCustomRendering says
		// this menu is not drawn through a Scaleform movie, which is true - it draws nothing at
		// all - and kInventoryItemMenu is what marks it as one of the item-viewing family the UI
		// 3D scene is rendered for.
		// The flags InventoryMenu actually carries, and ONLY those. It is the menu whose 3D we are
		// trying to reproduce, and CommonLibSSE records its set as:
		//     kPausesGame | kDisablePauseMenu | kUpdateUsesCursor | kInventoryItemMenu | kCustomRendering
		//
		// Two flags this menu used to set are gone, and both were mistakes of mine:
		//
		//  * kRendersOffscreenTargets - added only so PreDisplay would fire as a diagnostic. The
		//    inventory does NOT have it; of every menu open in gameplay only the HUD does. Its
		//    purpose is to send a menu's rendering to an OFFSCREEN target, which a blank movie
		//    would never composite - so it may well have been diverting our own render into a
		//    buffer nothing draws.
		//
		//  * kPausesGame - the inventory has it, but pausing the game because a settings page is
		//    open is a real cost to the player, and it changed nothing when tried.
		menuFlags.set(RE::UI_MENU_FLAGS::kCustomRendering,
					  RE::UI_MENU_FLAGS::kInventoryItemMenu,
					  RE::UI_MENU_FLAGS::kRequiresUpdate);

		// Still NOT kUsesCursor - stealing the cursor from the framework's own menu would be
		// visible to the player in a way this menu never should be.
		inputContext = Context::kNone;

		// The value IMenu itself defaults to, and what the inventory carries. It was 0 on the
		// first attempt, which put this menu below everything - and "rendered last" and "not
		// rendered" are indistinguishable from the outside.
		depthPriority = 3;

		// A REAL MOVIE. Some of what the game does for a menu is gated on it having a
		// GFxMovieView, and the entire purpose of this menu is to be treated as a real item menu -
		// so a menu with no movie may simply never qualify, however its flags are set.
		//
		// The movie is OURS and deliberately EMPTY: one blank frame, 20 bytes, generated by
		// .MD/scripts/make-blank-swf.py. Loading a vanilla SWF by path would have inherited
		// whatever that one draws (the fader paints the screen black), and another mod's file
		// would be someone else's asset.
		if (auto* scaleform = RE::BSScaleformManager::GetSingleton())
		{
			const bool loaded = scaleform->LoadMovieEx(
				this, "ApocryphaItemExplorer/preview",
				RE::BSScaleformManager::ScaleModeType::kShowAll, 0.0F,
				[](RE::GFxMovieDef*) {});
			logger::info("preview menu: blank movie {}", loaded ? "loaded" : "FAILED to load");
		}
	}

	RE::IMenu* PreviewMenu::Create()
	{
		return new PreviewMenu();
	}

	RE::UI_MESSAGE_RESULTS PreviewMenu::ProcessMessage(RE::UIMessage&)
	{
		// Every message is accepted and ignored. There is no movie to advance and no input to take.
		return RE::UI_MESSAGE_RESULTS::kHandled;
	}

	void PreviewMenu::PreDisplay()
	{
		// Kept only as evidence that the game renders this menu at all. The DRAW is in PostDisplay,
		// which is where the game's own menus do it.
		static bool logged = false;
		if (!logged)
		{
			logged = true;
			logger::info("preview menu: PreDisplay fired - the game IS rendering this menu");
		}
	}

	void PreviewMenu::PostDisplay()
	{
		// EXACTLY WHAT THE GAME'S INVENTORY DOES, IN THE ORDER IT DOES IT.
		//
		// InventoryMenu::PostDisplay is nine instructions. Its address came out of the live vtable
		// (slot 6, +0x88DAE0 on 1.5.97) and it disassembles to:
		//
		//     mov  rcx, [this+0x10]              ; uiMovie
		//     test rcx, rcx / je                 ; only if it has one
		//     call [rax+0x130]                   ; DISPLAY THE MOVIE FIRST
		//     mov  rcx, [Inventory3DManager]
		//     jmp  Inventory3DManager::Render    ; THEN the 3D
		//
		// Two things every earlier attempt had wrong. The ORDER: the 3D is rendered after the movie
		// is displayed, not before. And the CALL: a bare Render(), no light scheme and no camera -
		// so the scheme sweep and the hand-bound UI3DSceneManager render were both answering a
		// question the game never asks.
		IMenu::PostDisplay();

		if (auto* mgr = RE::Inventory3DManager::GetSingleton()) { mgr->Render(); }

		// Once only - this is per-frame code (rule 14).
		static bool logged = false;
		if (!logged)
		{
			logged = true;
			logger::info("preview menu: PostDisplay - movie displayed, then Inventory3DManager::Render");
		}
	}

	void RegisterPreviewMenu()
	{
		if (g_registered) { return; }

		auto* ui = RE::UI::GetSingleton();
		if (!ui)
		{
			// Rule 17: not ready is not never - this is called again at the next message.
			logger::debug("preview menu: the UI is not available yet; will register later");
			return;
		}

		ui->Register(PreviewMenu::MENU_NAME, PreviewMenu::Create);
		g_registered = true;
		logger::info("preview menu: registered \"{}\" (kCustomRendering | kInventoryItemMenu)",
					 std::string(PreviewMenu::MENU_NAME));
	}

	void SetPreviewMenuOpen(bool a_open)
	{
		if (!g_registered) { return; }
		if (PreviewMenuOpen() == a_open) { return; }

		auto* queue = RE::UIMessageQueue::GetSingleton();
		if (!queue) { return; }

		queue->AddMessage(RE::BSFixedString(std::string(PreviewMenu::MENU_NAME).c_str()),
						  a_open ? RE::UI_MESSAGE_TYPE::kShow : RE::UI_MESSAGE_TYPE::kHide,
						  nullptr);
		logger::info("preview menu: asked to {} it", a_open ? "open" : "close");
	}

	bool PreviewMenuOpen()
	{
		auto* ui = RE::UI::GetSingleton();
		return ui && ui->IsMenuOpen(PreviewMenu::MENU_NAME);
	}
}
